[phases.setup]
nixPkgs = ["python310", "chromium"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt",
  "python -m pip install webdriver-manager"
]

[phases.build]
cmds = []

[start]
cmd = "python trader.py"

