[phases.setup]
nixPkgs = ["python310", "chromium", "chromiumDriver"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python trader.py"

[variables]
GOOGLE_CHROME_BIN = "/nix/store/*/chromium-*/bin/chromium"
CHROMEDRIVER_PATH = "/nix/store/*/chromium-*/bin/chromedriver"

